### ISSUE TITLE
Require a pull request

### ISSUE THREAD

**Issue by lazzarello** [noisebridge/gung-heap#2]
Seriously, do you really want to be sorting through .zip archives and committing other people's stuff? I sure don't. PR or GTFO.

**Comment by robbintt** [comment]
I'm going to err on the side of including people who never learned to git 😅. If the workflow is too costly I can stop doing it. All i have to do is connect the upstream repository, pull, branch, review commit, and push.  The only issue is that this will probably be over 25-50 megabytes (email limit) pretty quickly.
